baseURL = "https://sleepy-wilson-e5c9f4.netlify.com/"
languageCode = "en-us"
title = "Geordie Test Atelier"
theme = "meghna"
summaryLength = 10

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "Sponsorship"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Atelier"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Crew"
    URL = "our-team"
    weight = 5

# Site params
[params]
home= "Home"
logo = "images/logo.png"

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/computer.jpg"
    heading = "Geordie Test Atelier"
    content= "Newcastle's first, last and only diverse, accessible, DIY, punk, eco-friendly, inclusive, non-profit Software Testing conference"
    btn = true
    btnText="I NEED A Ticket"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "We are Seeking Sponsors"
    content = "Would you like to help us make the magic happen?"
    btnURL = "services"
    btnText = "Sponsor Us"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Accessible Venue"
        icon = "tf-ion-key"
        count = "1"

        [[params.counter.counterItem]]
        title = "Tickets Available"
        icon = "tf-ion-card"
        count = "80"

        [[params.counter.counterItem]]
        title = "Amazing Speakers"
        icon = "tf-ion-happy"
        count = "12"

        [[params.counter.counterItem]]
        title = "Bugs Squished"
        icon = "tf-ion-bug"
        count = "2,147,483,649"